### ISSUE TITLE
怎么使用？

### ISSUE THREAD

**Issue by Seanxwy** [maliming/WeChatPay#1]

**Comment by maliming** [comment]
https://github.com/maliming/WeChatPay/blob/master/WeChatPay/IWeChatPayManager.cs

功能都在这个类中, 首先你要看懂微信的文档.

**Comment by Seanxwy** [comment]
我觉得你得代码写得很优雅，比别得支付组件干净利落很多。希望能做一个用例教大家使用。

**Comment by maliming** [comment]
如果你愿意提供一个微信支付商户信息. 我可以抽时间完善一下这个类库.

**Comment by Seanxwy** [comment]
怎么提供？

**Comment by maliming** [comment]
Q 4456337
