### ISSUE TITLE
构造函数无法获取到值

### ISSUE THREAD

**Issue by Seanxwy** [maliming/WeChatPay#2]
services.AddTransient<IWechatPayConfiguration, WechatPayConfiguration>();
services.AddTransient<IWeChatPayManager, WeChatPayManager>();

在WeChatPayManager得构造函数中，无法获取到对应得值。我知道我应该是哪里没处理好。这个问题应该如何处理

**Comment by maliming** [comment]
这取决你的依赖注入容器. 你可以使用工厂方法添加到依赖注入中.
