### ISSUE TITLE
你好，这个可以放到unity中使用吗？

### ISSUE THREAD

**Issue by ShenKang4181** [maliming/WeChatPay#3]
可以调起微信支付吗？

**Comment by maliming** [comment]
没有试过. 你可以自己根据微信文档试试.

**Comment by ShenKang4181** [comment]
你这个是怎么弄的，你这个工程也能打出apk吗？unity里面砍掉了很多名字空间，这个在unity里不能使用除非我补全他，估计需要花费半天，但是我现在不知道你这个能不能调起微信app然后支付，所以问一下------------------ 原始邮件 ------------------
发件人: "maliming"<notifications@github.com>
发送时间: 2019年6月19日(星期三) 晚上7:43
收件人: "maliming/WeChatPay"<WeChatPay@noreply.github.com>;
抄送: "ShenKang4181"<1284784181@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [maliming/WeChatPay] 你好，这个可以放到unity中使用吗？ (#3)



没有试过. 你可以自己根据微信文档试试.
 
&mdash;

**Comment by maliming** [comment]
这是开源的, 请自行查看.
